<?php

/**
 * Created by PhpStorm.
 * User: kafa
 * Date: 03.11.2017
 * Time: 15:14
 */
class MDN_Siteblock1_Model_Block extends Mage_Core_Model_Abstract
{
    public function _construct()
    {
        parent::_construct(); // TODO: Change the autogenerated stub
        $this->_init('siteblock1/block');
    }
}